server:
  port: 8888
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/studentInfo
    username: root
    password: a
  mvc:
    view:
      prefix: /pages/
      suffix: .jsp
mybatis:
  mapper-locations:
  - classpath:com/yc/studentinfo/mapper/*Mapper.xml
  type-aliases-package: com.yc.studentinfo.beans